# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-20 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20180120_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={},
        ),
    ]
